webapi:
  build: .
  dockerfile: Dockerfile-dev
  command: serve
  volumes:
    - src:/app/src
    - gulpfile.js:/app/gulpfile.js
    - .jscsrc:/app/.jscsrc
    - .jshintrc:/app/.jshintrc

db:
  image: rethinkdb:latest
  volumes:
    - data:/data
